const cartActionTypes = {
    TOGGLE_CART_DROPDOWN: 'TOGGLE_CART_DROPDOWN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    SET_CART_ITEMS: 'SET_CART_ITEMS'
}

export const localCartActionTypes = {
    TOGGLE_LOCAL_CART_DROPDOWN: 'TOGGLE_LOCAL_CART_DROPDOWN',
    ADD_LOCAL_ITEM: 'ADD_LOCAL_ITEM',
    REMOVE_LOCAL_ITEM: 'REMOVE_LOCAL_ITEM',
    CLEAR_ITEM_FROM_LOCAL_CART: 'CLEAR_ITEM_FROM_LOCAL_CART',
    SET_LOCAL_CART_ITEMS: 'SET_LOCAL_CART_ITEMS'
}

export default cartActionTypes;