const userActionTypes = {
    SET_AUTH_USER: 'SET_AUTH_USER',
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    SIGN_OUT_USER: 'SIGN_OUT_USER',
    IS_USER_PERSISTED: 'IS_USER_PERSISTED'
}

export default userActionTypes;